---
title: "Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---
## Glass Data
```{r}
library(tidyverse)
```

Read in data, assign column names
```{r}
glass.data <- read_csv("https://www4.stat.ncsu.edu/~online/datasets/glass.data", col_names = c("ID", "RI", "Na", "Mg", "Al", "Si", "K", "Ca", "Ba", "Fe", "Type_of_glass"))
glass.data
```

Change type_of_glass variable with mutate
```{r}
glass.data <- glass.data %>% mutate(Type_of_glass = ifelse(Type_of_glass == 1, "building_windows_float_processed", ifelse(Type_of_glass == 2, "building_windows_non_float_processed", ifelse(Type_of_glass == 3, "vehicle_windows_float_processed", ifelse(Type_of_glass == 4, "vehicle_windows_non_float_processed", ifelse(Type_of_glass == 5, "containers", ifelse(Type_of_glass == 6, "tableware", ifelse(Type_of_glass == 7, "headlamps", NA))))))))
glass.data
```

Continue chain to include Fe < .2 and glass is tableware or headlamps 
```{r}
glass.data |>
  filter(Fe <= 0.2, Type_of_glass == "tableware" | Type_of_glass == "headlamps")
```
## Yeast Data

Read in yeast data
```{r}
yeast.data <- read_fwf("https://www4.stat.ncsu.edu/online/datasets/yeast.data", fwf_widths(c(12, 6, 6, 6, 6, 6, 6, 6, 6, 3), c("seq_name", "mcg", "gvh", "alm", "mit", "erl", "pox", "vac", "nuc", "class")))
yeast.data
```

Chain that removes seq_name and nuc columns and adds mean and median for each class grouping
```{r}
yeast.data <- yeast.data%>%
  select("mcg", "gvh", "alm", "mit", "erl", "pox", "vac", "class") %>%
  group_by(class) %>%
  summarise(across(mcg:vac, list(mean = mean, median = median), .names = "{.col}_{.fn}"))
yeast.data
```
```

